import * as vscode from 'vscode';

export class SettingsPanel implements vscode.Disposable {
  private panel?: vscode.WebviewPanel;
  private disposable?: vscode.Disposable;
  open(): void {
    if(this.panel){this.panel.reveal(vscode.ViewColumn.Beside,false);this.panel.webview.html=this.html();return;}
    this.panel=vscode.window.createWebviewPanel('codenote.settings','CodeNote Settings',vscode.ViewColumn.Beside,{enableScripts:true,retainContextWhenHidden:true});
    this.disposable=this.panel.webview.onDidReceiveMessage(async m=>{
      if(m?.type==='save'&&m.values){const cfg=vscode.workspace.getConfiguration('codenote');for(const [k,v] of Object.entries(m.values))await cfg.update(k,v,vscode.ConfigurationTarget.Global);vscode.window.setStatusBarMessage('CodeNote settings saved',1800);}
      if(m?.type==='reset'){const cfg=vscode.workspace.getConfiguration('codenote');for(const k of ['liveVisualMode','inlineKindHints','inlineShowTags','inlineRenderDelay','inlineBoundaryStyle','inlineBoundarySymbol','inlineBoundaryLabel','shortcut.noteTrigger','shortcut.headingTrigger','shortcut.paragraphTrigger','study.defaultFocusNotes','study.showSidebar','study.lineNumbers','snap.defaultTemplate','snap.lineNumbers','snap.branding'])await cfg.update(k,undefined,vscode.ConfigurationTarget.Global);this.panel!.webview.html=this.html();}
    });
    this.panel.onDidDispose(()=>{this.disposable?.dispose();this.disposable=undefined;this.panel=undefined;});
    this.panel.webview.html=this.html();
  }
  dispose():void{this.disposable?.dispose();this.panel?.dispose();}
  private html():string{
    const c=vscode.workspace.getConfiguration('codenote');const nonce=Math.random().toString(36).slice(2);
    const data=JSON.stringify({liveVisualMode:c.get('liveVisualMode',true),inlineKindHints:c.get('inlineKindHints',false),inlineShowTags:c.get('inlineShowTags',false),inlineRenderDelay:c.get('inlineRenderDelay',18),inlineBoundaryStyle:c.get('inlineBoundaryStyle','symbol'),inlineBoundarySymbol:c.get('inlineBoundarySymbol','◆'),inlineBoundaryLabel:c.get('inlineBoundaryLabel',false),'shortcut.noteTrigger':c.get('shortcut.noteTrigger','--'),'shortcut.headingTrigger':c.get('shortcut.headingTrigger','#'),'shortcut.paragraphTrigger':c.get('shortcut.paragraphTrigger','!!'),'study.defaultFocusNotes':c.get('study.defaultFocusNotes',false),'study.showSidebar':c.get('study.showSidebar',true),'study.lineNumbers':c.get('study.lineNumbers',true),'snap.defaultTemplate':c.get('snap.defaultTemplate','aurora'),'snap.lineNumbers':c.get('snap.lineNumbers',true),'snap.branding':c.get('snap.branding',false)}).replace(/</g,'\\u003c');
    return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}';"><style nonce="${nonce}">
    *{box-sizing:border-box}body{font:13px var(--vscode-font-family);color:var(--vscode-foreground);background:var(--vscode-editor-background);margin:0}.top{position:sticky;top:0;z-index:4;display:flex;align-items:center;justify-content:space-between;padding:14px 22px;border-bottom:1px solid var(--vscode-panel-border);background:var(--vscode-editor-background)}h1{font-size:18px;margin:0}.actions{display:flex;gap:8px}button{border:0;border-radius:6px;padding:8px 13px;background:var(--vscode-button-background);color:var(--vscode-button-foreground);cursor:pointer;font-weight:650}.secondary{background:var(--vscode-button-secondaryBackground);color:var(--vscode-button-secondaryForeground)}main{max-width:760px;padding:26px 22px 60px}.card{border:1px solid var(--vscode-panel-border);border-radius:10px;padding:18px;margin-bottom:16px;background:var(--vscode-sideBar-background)}h2{font-size:14px;margin:0 0 14px}.row{display:grid;grid-template-columns:1fr 220px;gap:18px;align-items:center;padding:10px 0;border-top:1px solid color-mix(in srgb,var(--vscode-panel-border) 55%,transparent)}.row:first-of-type{border-top:0}.desc{opacity:.66;font-size:11px;margin-top:3px;line-height:1.45}input[type=text],input[type=number],select{width:100%;padding:7px 9px;background:var(--vscode-input-background);color:var(--vscode-input-foreground);border:1px solid var(--vscode-input-border,transparent);border-radius:5px}.preview{font-family:var(--vscode-editor-font-family);padding:12px;border-radius:7px;background:var(--vscode-textCodeBlock-background);line-height:1.65;margin-top:10px}.mark{color:var(--vscode-descriptionForeground)}</style></head><body>
    <div class="top"><div><h1>.cnote settings</h1><div class="desc">Personalize how notes read without touching source code.</div></div><div class="actions"><button class="secondary" id="reset">Reset</button><button id="save">Save settings</button></div></div><main>
    <section class="card"><h2>Inline visual notes</h2><div class="row"><div>Automatic visual mode<div class="desc">Show clean notes whenever the caret leaves the comment block.</div></div><input id="liveVisualMode" type="checkbox"></div><div class="row"><div>Kind labels<div class="desc">Show labels such as Warning, Quiz or Definition.</div></div><input id="inlineKindHints" type="checkbox"></div><div class="row"><div>Tags<div class="desc">Show #tags inline.</div></div><input id="inlineShowTags" type="checkbox"></div><div class="row"><div>Render delay<div class="desc">Milliseconds before a completed note becomes visual.</div></div><input id="inlineRenderDelay" type="number" min="0" max="250"></div></section>
    <section class="card"><h2>Note boundaries</h2><div class="row"><div>Boundary style<div class="desc">Keeps opener/closer rows visible so visual mode has exactly the same line count as source mode.</div></div><select id="inlineBoundaryStyle"><option value="symbol">Symbol</option><option value="line">Line</option><option value="none">None</option></select></div><div class="row"><div>Boundary symbol<div class="desc">Try ◆ ✦ ● ▸ 📘 or any short marker.</div></div><input id="inlineBoundarySymbol" type="text" maxlength="12"></div><div class="row"><div>Show note type on opening boundary</div><input id="inlineBoundaryLabel" type="checkbox"></div><div class="preview"><span class="mark" id="openMark">◆</span><br><b>Vectors</b><br>Vectors are dynamic arrays.<br><span class="mark" id="closeMark">◆</span></div></section>
    <section class="card"><h2>Typing shortcuts</h2><div class="row"><div>Line note trigger<div class="desc">Type this at the start of a line, then Space, to create a one-line note.</div></div><input id="shortcut.noteTrigger" type="text" maxlength="12"></div><div class="row"><div>Heading trigger<div class="desc">Type this at the start of a line, then Space, to create a one-line heading. Example: use @ if # feels wrong.</div></div><input id="shortcut.headingTrigger" type="text" maxlength="12"></div><div class="row"><div>Definition trigger<div class="desc">Type this at the start of a line, then Space, to create a definition note.</div></div><input id="shortcut.paragraphTrigger" type="text" maxlength="12"></div><div class="preview"><span class="mark">trigger + Space</span><br><b id="shortcutPreview">-- → note · # → heading · !! → definition</b></div></section>
    <section class="card"><h2>Study defaults</h2><div class="row"><div>Open in Focus Notes<div class="desc">Hide code behind placeholders until you choose to show it.</div></div><input id="study.defaultFocusNotes" type="checkbox"></div><div class="row"><div>Section sidebar</div><input id="study.showSidebar" type="checkbox"></div><div class="row"><div>Code line numbers</div><input id="study.lineNumbers" type="checkbox"></div></section>
    <section class="card"><h2>Snap Studio defaults</h2><div class="row"><div>Default template</div><select id="snap.defaultTemplate"><option>aurora</option><option>midnight</option><option>sunset</option><option>forest</option><option>paper</option><option>minimal</option><option>ocean</option><option>lavender</option></select></div><div class="row"><div>Line numbers</div><input id="snap.lineNumbers" type="checkbox"></div><div class="row"><div>.cnote branding</div><input id="snap.branding" type="checkbox"></div></section></main>
    <script nonce="${nonce}">const vscode=acquireVsCodeApi(),D=${data};const ids=['liveVisualMode','inlineKindHints','inlineShowTags','inlineRenderDelay','inlineBoundaryStyle','inlineBoundarySymbol','inlineBoundaryLabel','shortcut.noteTrigger','shortcut.headingTrigger','shortcut.paragraphTrigger','study.defaultFocusNotes','study.showSidebar','study.lineNumbers','snap.defaultTemplate','snap.lineNumbers','snap.branding'];for(const id of ids){const e=document.getElementById(id),v=D[id];if(e.type==='checkbox')e.checked=!!v;else e.value=String(v??'');}function prev(){const st=document.getElementById('inlineBoundaryStyle').value,s=document.getElementById('inlineBoundarySymbol').value||'◆',l=document.getElementById('inlineBoundaryLabel').checked;document.getElementById('openMark').textContent=st==='none'?'':st==='line'?'╭─'+(l?' Note':''):s+(l?' Note':'');document.getElementById('closeMark').textContent=st==='none'?'':st==='line'?'╰─':s;const nt=document.getElementById('shortcut.noteTrigger')?.value||'--',ht=document.getElementById('shortcut.headingTrigger')?.value||'#',pt=document.getElementById('shortcut.paragraphTrigger')?.value||'!!';const sp=document.getElementById('shortcutPreview');if(sp)sp.textContent=nt+' → note · '+ht+' → heading · '+pt+' → definition';}['inlineBoundaryStyle','inlineBoundarySymbol','inlineBoundaryLabel','shortcut.noteTrigger','shortcut.headingTrigger','shortcut.paragraphTrigger'].forEach(id=>document.getElementById(id).addEventListener('input',prev));prev();document.getElementById('save').onclick=()=>{const values={};for(const id of ids){const e=document.getElementById(id);values[id]=e.type==='checkbox'?e.checked:e.type==='number'?Number(e.value):e.value;}vscode.postMessage({type:'save',values});};document.getElementById('reset').onclick=()=>vscode.postMessage({type:'reset'});</script></body></html>`;
  }
}
